# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160212_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.BooleanField(default=False),
        ),
    ]
