# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20160212_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
