# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 23:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20160212_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateField(default=datetime.date(2016, 2, 12)),
        ),
    ]
