# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20160212_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
