# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20160212_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='myuser',
            name='fav_food',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='myuser',
            name='fav_sport',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='myuser',
            name='postal',
            field=models.TextField(default=''),
        ),
    ]
